@startuml
skinparam svgDimensionStyle false
hide empty description 
[*] -> ready : External post of Communication resource
state ready {
  state queued #lightblue {
  }
}
ready --> in_review
queued : Request received\nbut not reviewed

state in_progress {
  state in_review #lightblue{
  }
  state waiting_for_information #lightblue{
  }
  state accepted #lightblue{
  }
  state partial_accept #lightblue{
  }
}
in_review --> waiting_for_information
in_review --> accepted
in_review --> partial_accept
in_review --> in_review: Inform requester on\nadditional time needed
waiting_for_information --> in_review
in_review --> denied
accepted --> amendment_completed
denied -down-> disagreement_logged
waiting_for_information : e.g. Additional Information Needed
accepted : Decision made to accept
partial_accept : Decision made that\npart of request is accepted\nand part is denied,\ndisagreement can be logged
denied : Decision made to deny,\ndisagreement can be logged

state cancelled {
  state requester_cancelled #lightblue {
  }
}
cancelled --> [*]
ready --> cancelled
in_progress --> cancelled
requester_cancelled : Requester decided to cancel\nthe request for correction

state complete {
 state amendment_completed #lightblue{
 }
 state disagreement_logged #lightblue{
 }
 state denied #lightblue{
 }
 state inform_rebuttal_option #lightblue{
 }
 state partial_amendment_completed #lightblue{
  }
}
partial_accept --> partial_amendment_completed
disagreement_logged --> inform_rebuttal_option
denied -down-> inform_rebuttal_option
partial_accept --> inform_rebuttal_option: Communication to inform\non rebuttal option
complete --> [*]

state Task.status{
}
state Task.businessStatus #lightblue {
}
@enduml
