@startuml
[*] -> ready: External post of\nCommunication resource
state ready {
  state Queued #lightblue {
  }
}
ready --> In_Review
Queued : Request received but not reviewed

state inprogress {
  state In_Review #lightblue{
  }
  state WaitingOnInformation #lightblue{
  }
  state Accepted #lightblue{
  }
  state PartialAccept #lightblue{
  }
}
In_Review --> WaitingOnInformation
In_Review --> Accepted
In_Review --> PartialAccept
In_Review --> In_Review: Inform requester on additional time needed
WaitingOnInformation --> In_Review
In_Review --> Denied
PartialAccept --> AmendmentCompleted
PartialAccept --> DisagreementLogged
Accepted --> AmendmentCompleted
Denied -> DisagreementLogged
WaitingOnInformation : e.g. Additional Information Needed
Accepted : Decision made to accept
PartialAccept : Decision made that part of\nrequest is accepted and\npart is denied,\ndisagreement can be logged
Denied : Decision made to deny,\ndisagreement can be logged

state cancelled {
  state Nevermind #lightblue {
  }
}
ready --> cancelled
inprogress --> cancelled
Nevermind : Requester decided to cancel\nthe request for correction

state complete {
 state AmendmentCompleted #lightblue{
 }
 state DisagreementLogged #lightblue{
 }
 state Denied #lightblue{
 }
 state InformRebuttalOption #lightblue{
 }
}
DisagreementLogged -> InformRebuttalOption
Denied -> InformRebuttalOption
PartialAccept -> InformRebuttalOption: Communication to inform\non rebuttal option
complete --> [*]

state Task.status{
}
state Task.businessStatus #lightblue {
}
@enduml
