@startuml
title Restful Interactions for Request For Correction Using Task Alone


note left of CorrectionRequester
Send a new Correction Request
end note
CorrectionRequester->RequestFulfiller: Create (POST) Task
activate RequestFulfiller
RequestFulfiller->RequestFulfiller: start internal processing


loop
note left of CorrectionRequester
Poll periodically to check for 
correspondence and status of the 
correction request until completed
end note
CorrectionRequester->RequestFulfiller: Read (GET) Task
CorrectionRequester -> CorrectionRequester: process and react
alt
note left of CorrectionRequester
Correspond with Fulfiller
end note
CorrectionRequester->RequestFulfiller: Update (PUT) Task
end

end

alt
note right of RequestFulfiller
When the request is fulfilled
(agreed or rejected) then 
the Task is updated
end note
RequestFulfiller->RequestFulfiller: finish internal processing
CorrectionRequester->RequestFulfiller: Read (GET) Task
CorrectionRequester -> CorrectionRequester: process and react
end

Deactivate RequestFulfiller
note left of CorrectionRequester: smile
@enduml