@startuml
title Abstract Model - Update to a Request For Correction

note left of CorrectionRequester
Notice a problem
end note

CorrectionRequester->RequestFulfiller : Request a Change
Activate RequestFulfiller
RequestFulfiller->RequestFulfiller : Check records

== Time goes by ==
note left of CorrectionRequester
Realize more information is needed
end note
CorrectionRequester->RequestFulfiller : Update the Change Request
RequestFulfiller->RequestFulfiller : Check records

== Further processing ==
@enduml