@startuml
skinparam DefaultTextAlignment center
skinparam SequenceMessageAlignment direction
skinparam Padding 2
skinparam ParticipantPadding 60
skinparam LifelineStrategy solid
autonumber "<b>[###]</b>"

participant R [
  **Requester**
  ----
  //FHIR Application//
]
participant F [
  **Fulfiller**
  ----
  //FHIR Server//
]

R->F : Request a Change

Activate F
  F->F : Check records
  F->F : Correction request is\nnot appropriate
  F->F : Change denied
  F->R : Request is complete
Deactivate F

@enduml
