@startuml
skinparam DefaultTextAlignment center
skinparam SequenceMessageAlignment direction
skinparam Padding 2
skinparam ParticipantPadding 60
skinparam LifelineStrategy solid
autonumber "<b>[###]</b>"

participant R [
  **Requester**
  ----
  //FHIR Application//
]
participant F [
  **Fulfiller**
  ----
  //FHIR Server//
]

group Request a Correction
  R->F : Request a Change
else Accept Correction Request
  Activate F
    F->R : Request Accepted
    F->F : Check records
    F->F : Decide correction is\nnot appropriate
    F->R : Request is complete
  Deactivate F
else Requester Agrees with Final Correction
  R->R : Review correction
end



@enduml
