@startuml
skinparam DefaultTextAlignment center
skinparam SequenceMessageAlignment direction
skinparam Padding 2
skinparam ParticipantPadding 60
skinparam LifelineStrategy solid
autonumber "<b>[###]</b>"

participant R [
  **Requester**
  ----
  //FHIR Application//
]
participant F [
  **Fulfiller**
  ----
  //FHIR Server//
]

group Request a Correction
  R->F : Request a Change
else Accept Correction Request
  Activate F
    F->R : Request Accepted
    F->F : Check records

  group Additional Information Needed
    F->R : Please provide documentation
    R->F : Here is the documentation
  end

  group Additional Information Needed
    F->R : Need the full documents
    R->F : Here are the //full// documents
  end

    F->F : Decide to make correction
    F->F : Change accepted
    F->R : Request is complete
  Deactivate F
else Requester Agrees with Final Correction
  R->R : Review correction
end



@enduml
