@startuml
title Abstract Model - Disagreement on a Denied Correction stays Denied

note left of CorrectionRequester
Previously had a Change Denied
end note


CorrectionRequester->RequestFulfiller : 3. Send a Disagreement
Activate RequestFulfiller
RequestFulfiller->RequestFulfiller : Record Disagreement
note right: Based on the arguments and data\ndecide to to continue to reject changing the record
loop Check Status
CorrectionRequester->RequestFulfiller : 6. Check status
end


RequestFulfiller->RequestFulfiller: Record Rebuttal
RequestFulfiller->CorrectionRequester: 5. Change remains Denied [with Rebuttal]
Deactivate RequestFulfiller

@enduml