@startuml
title Abstract Model - Request For Correction Partially Accepted
skinparam DefaultTextAlignment center
skinparam SequenceMessageAlignment direction
skinparam Padding 2
skinparam ParticipantPadding 60
skinparam LifelineStrategy solid
autonumber 4 "<b>[###]</b>"

participant CorrectionRequester [
  **Requester**
  ----
  //FHIR Application//
]
participant RequestFulfiller [
  **Fulfiller**
  ----
  //FHIR Server//
]

group Request a Correction

CorrectionRequester->RequestFulfiller : Request a Change
Activate RequestFulfiller
RequestFulfiller->RequestFulfiller : Check records

RequestFulfiller->RequestFulfiller : Decide to accept part of request\nand deny other part of request

RequestFulfiller->CorrectionRequester : Change partially accepted
RequestFulfiller->CorrectionRequester : Accepted part of request completed
Deactivate RequestFulfiller
end 
@enduml
