@startuml
' skinparam NoteTextAlignment center
skinparam DefaultTextAlignment center
skinparam Padding 2
skinparam ParticipantPadding 50
skinparam LifelineStrategy solid


:Patient or representative
finds issue in record;

:""CorrectionRequest"" Communication
from **Requester** to **Fulfiller**;

repeat :**Fulfiller** request processing;
    switch (**Fulfiller** state)
        case (Received)
            ://Optional// Communication
            Status update
            **Fulfiller** to **Requester**;
        case (Needs additional information)
            :Communication
            Request information
            **Fulfiller** to **Requester**;
            ://Wait// for Communication
            from **Requester**;
        case (Accepted) 
            :Communication
            Status update
            **Fulfiller** to **Requester**;
        case (Partially Accepted) 
            :Communication
            Status update
            **Fulfiller** to **Requester**;
        case (Denied)
            :Communication
            Status update
            **Fulfiller** to **Requester**;
    endswitch

repeat while (Request is //completed//) is (no)

if (**Requester** disagrees) is (yes) then
    :**Requester** submits a //disagreement//;

    repeat :**Fulfiller** disagreement processing
        switch (**Fulfiller** state)
            case (Logged) 
                :Communication
                Status update
                **Fulfiller** to **Requester**;
            case (Amended) 
                :Communication
                Status update
                **Fulfiller** to **Requester**;
            case (Partially Amended) 
                :Communication
                Status update
                **Fulfiller** to **Requester**;
            case (Denied)
                :Communication
                Status update
                **Fulfiller** to **Requester**;
        endswitch
    repeat while (Disagreement is //completed//) is (no)
else (no)
endif

:Done;


@enduml